import re

TEXFILE = "Jaakkothesis.tex"
BIBFILE = "autogenerated.bib"

with open(TEXFILE, "r", encoding="utf-8") as f:
    tex_content = f.read()

cite_keys = set(re.findall(r'\\cite\{([^}]+)\}', tex_content))

with open(BIBFILE, "w", encoding="utf-8") as f:
    for key in cite_keys:
        f.write(f"@misc{{{key},\n  note = {{Autogenerated placeholder entry}}\n}}\n\n")

print(f"BibTeX file '{BIBFILE}' generated with {len(cite_keys)} entries.")
